src/pages/WhoWeAre.tsx

Fix typo under Alison's title 

[NO-TICKET] Fix Typo

---

src/components/layout/Footer.tsx
src/components/layout/Header.tsx

Updates to Header
[DES-13](https://artistguide.atlassian.net/browse/DES-13)
Update to the header for constraints on bigger screens
**Phone Landscape**
**Phone Portrait**
**Large Desktop**
**Small Desktop**
**Tablet Landscape**
**Tablet Portait**

[DES-13] Header Updates

---

src/components/SignUp/SignUpFooter.tsx
src/pages/SignUp.tsx
src/theme/styleVars.ts

[DEV-137](https://artistguide.atlassian.net/browse/DEV-137)
Added basic pagination in style rather than just text

[DEV-137] Basic Pagination for Sign Up Flow

---

src/components/ScrollToTop.tsx
src/components/layout/Footer.tsx
src/pages/App.tsx
src/pages/FAQ.tsx

* Added ScrollToTop Component
* Updated FAQ page to add key=, to get rid of Console Error.

[DES-16] ScrollToTop

---

src/components/SignUp/SignUpFooter.tsx
src/pages/SignUp.tsx

- Add logic for Privacy Agreement in Sign Up footer navigation
- Add some comments to the code

[NO-TICKET] Sign Up: Privacy Agreement Navigation Logic

---

src/components/SignUp/Landing.tsx
src/styles/custom.scss

[DEV-138](https://artistguide.atlassian.net/browse/DEV-138)
Providing a base styling example for the sign up landing page

[DEV-138] Base Styling Example for Sign-Up Landing Step

---

src/components/Home/WhoSquare.tsx
src/components/WhoWeAre/Team.tsx
src/components/layout/Titles.tsx
src/index.tsx
src/pages/App.tsx
src/styles/custom.scss
src/theme/globalStyles.ts
src/theme/styleVars.ts

Updating Fonts to pull correctly
[DES-18](https://artistguide.atlassian.net/browse/DES-18)
Updating the fonts on-system to show correctly.  

[DES-18] Update Fonts

---

package-lock.json
package.json
server.js
src/api/endpoints.ts

Creating the necessary infrastructure we'll need for Axios for our API calls, as well as creating the mock node server. 

[NO-TICKET] Set Up Endpoints Infra Using Axios and Mock Server with Proxy

---

src/components/SignUp/ActorInfo1.tsx
src/components/SignUp/Basics.tsx
src/components/SignUp/Privacy.tsx
src/components/SignUp/SignUpFooter.tsx
src/genericComponents/Button.tsx
src/theme/styleVars.ts

[NO-TICKET] Button Style Improvements and Sign Up Flow Tweaks

---

src/components/SignUp/ActorInfo2.tsx
src/pages/SignUp.tsx

[DEV-142](https://artistguide.atlassian.net/browse/DEV-142)
Adding the Actor Info 2 step

[DEV-142] Sign-Up Step: Actor Info 2

---

src/components/SignUp/ActorInfo2.tsx

[FE-142](https://artistguide.atlassian.net/browse/FE-142)

[FE-142] Update Age Ranges for Actor Info 2 Page

---

src/components/SignUp/ProfilePhoto.tsx

This is the basic layout of the sign up flow profile upload step. It still needs some tweaks and a functioning BE endpoint to upload to and receive a URL back from. At that point, we can add the real functionality + tweak the design. 

[DEV-144] Sign Up Flow Step 7: Profile Photo Upload Page

---

public/index.html
src/components/layout/Footer.tsx
src/components/layout/Header.tsx
src/pages/App.tsx
src/pages/Donate.tsx

**Epic:** [DEV-209](https://artistguide.atlassian.net/browse/DEV-209)
Adding the Donate page

[DEV-209] Add Donate Page

---

src/components/SignUp/ActorInfo1.tsx
src/components/SignUp/ActorInfo2.tsx
src/components/SignUp/AdditionalSkills.tsx
src/components/SignUp/Awards.tsx
src/components/SignUp/Credits.tsx
src/components/SignUp/OffstageRoles.tsx
src/components/SignUp/SignUp2Footer.tsx
src/components/SignUp/Training.tsx
src/components/SignUp/Upcoming.tsx
src/genericComponents/GenericAccordion.tsx
src/pages/App.tsx
src/pages/Profile.tsx
src/pages/SignUp.tsx
src/pages/SignUp2.tsx

NO-TICKET
This PR:
1. Creates the second sign up flow component, footer, and its step components. We couldn't use the first sign up flow footer component because it has too much specific logic based on those steps. 
2. Fixes some minor react warnings about missing keys
3. Fixes accordion button
4. Adds the Profile component with a preview mode to work within the sign up flow

[NO-TICKET] Create New Sign Up 2 Components

---

src/components/SignUp/ActorInfo1.tsx
src/components/SignUp/ActorInfo2.tsx
src/components/SignUp/Privacy.tsx
src/genericComponents/PrivateLabel.tsx
src/theme/styleVars.ts

[DEV-222](https://artistguide.atlassian.net/browse/DEV-222)
Created new generic component to use as privacy label throughout sign-up flow.
Imported into current sign-up flow: Privacy, Actor1, & Actor2.
Minor deletions of previous span/placeholder code for privacy label.
N/A
- [√ ] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [√ ] You have tested these changes locally by running the app and letting it build successfully
- [√] Eslint ran successfully upon commit and `--force` was not used to force this PR
At least **1** PR approval is required by a Tech Lead to be merged. **2** approvals …

[DEV-222] Create Privacy Label (Sign-Up Flow)

---

src/components/SignUp/Credits.tsx

[NO-TICKET] Fix Linting Errors for Credits Page

---

src/components/SignUp/AdditionalSkills.tsx

[DEV150](https://artistguide.atlassian.net/browse/DEV-150)
Created the final step, 'Additional Skills' for sign-up flow 2. Includes checkbox portion for default skills and manually-entered input tags for any additional skills.
**Screenshots:**
- [√] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [√] You have tested these changes locally by running the app and letting it build successfully
- [√] Eslint ran successfully upon commit and `--force` was not used to force this PR

[DEV-150] Additional Skills Sign Up Flow 

---

src/api/endpoints.ts

[NO-TICKET] Update API URL

---

src/components/Home/Mailchimp.tsx
src/components/layout/BlobBox.tsx
src/components/layout/CardBox.tsx
src/components/layout/ForArtists.tsx
src/components/layout/ForTheatres.tsx
src/genericComponents/DividerBar.tsx
src/pages/Home.tsx

NO TICKET
Making new homepage design responsive

[NO-TICKET] Make New Homepage Design Responsive

---

src/components/SignUp/Basics.tsx

added form validation for signup. Will give red text if empty for first/last name, email, 18 over box not checked, and if email not in valid email format
- [X ] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [ X] You have tested these changes locally by running the app and letting it build successfully

[DEV-219] sign up form validation

---

.gitignore
src/components/SignUp/Basics.tsx
src/components/layout/Footer.tsx
src/pages/App.tsx
src/pages/FAQ.tsx
src/pages/SignUp.tsx
src/pages/TheaterResources.tsx
src/theme/styleVars.ts

[DEV228](https://artistguide.atlassian.net/browse/DEV-228)
Added a new theatre resources page to the CAG site.
- [✓] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [✓] You have tested these changes locally by running the app and letting it build successfully
- [✓] Eslint ran successfully upon commit and `--force` was not used to force this PR

[DEV-228] Added Theater Resources Page Base

---

src/pages/Profile.tsx

[DEV-229](https://artistguide.atlassian.net/browse/DEV-229)
Added filler message to notify user about completion of sign up flow (1) and of upcoming beta version which will include sign up flow 2.
- [✓] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [✓] You have tested these changes locally by running the app and letting it build successfully
- [✓] Eslint ran successfully upon commit and `--force` was not used to force this PR

[DEV-229] Added Sign Up Flow End Message

---

src/components/SignUp/SignUpFooter.tsx
src/pages/SignUp.tsx

[DEV-240](https://artistguide.atlassian.net/browse/TICKET)
Fixing the dynamic step reordering based on role selection

[DEV-240] Fix Dynamic Steps

---

src/components/SignUp/ActorInfo2.tsx
src/genericComponents/PrivateLabel.tsx
src/pages/Profile.tsx

[DEV-243](https://artistguide.atlassian.net/browse/DEV-243)
Make labels smaller for the two columns of checkboxes/radio buttons at the bottom of the ActorInfo2 page (details 2). 
N/A
- [√] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [√] You have tested these changes locally by running the app and letting it build successfully
- [√] Eslint ran successfully upon commit and `--force` was not used to force this PR

[Dev-243] Updated ActorInfo2; Made Private Labels Smaller

---

src/components/SignUp/Basics.tsx
src/components/SignUp/SignUpFooter.tsx
src/genericComponents/Input.tsx
src/pages/SignUp.tsx
src/utils/validation.ts

NO-TICKET
Adding in a lot of groundwork for form validation/required field functionality with examples on how to use them using the Basics page

[NO-TICKET] Form Validation Utils, Paradigms, and Basics Installation

---

src/components/SignUp/ActorInfo2.tsx
src/components/SignUp/Landing.tsx
src/components/layout/Titles.tsx
src/genericComponents/PrivateLabel.tsx
src/pages/Profile.tsx
src/theme/styleVars.ts

[DEV-245](https://artistguide.atlassian.net/browse/DEV-245)
[DEV-246](https://artistguide.atlassian.net/browse/DEV-246)
[DEV-247](https://artistguide.atlassian.net/browse/DEV-247)
[DEV-248](https://artistguide.atlassian.net/browse/DEV-248)
[DEV-250](https://artistguide.atlassian.net/browse/DEV-250)
Minor styling updates were made to the landing pages on sign up flow. (Combined tickets 245-248, 250)
N/A
- [√] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [√] You have tested these changes locally by running the app and letting it build successfully
- [√] Eslint ran successfully upon commit and `--force` was not used to force this PR
_Make sure you **squash …

[Dev-245] Minor styling and design updates 

---

src/components/SignUp/Demographics.tsx
src/components/SignUp/Upcoming.tsx
src/pages/SignUp2.tsx

[DEV-148](https://artistguide.atlassian.net/browse/DEV-148)
Adding the Upcoming Shows Step to the second half of the artist sign-up flow. Proper styling to come.

[DEV-148] Upcoming Shows Step

---

src/components/SignUp/ActorInfo1.tsx
src/components/SignUp/ActorInfo2.tsx
src/components/SignUp/Basics.tsx
src/pages/SignUp.tsx

[DEV-238](https://artistguide.atlassian.net/browse/DEV-238)
Add required fields functionality for Actor Info 1 and Actor Info 2 Steps

[DEV-238] Required Fields for Actor Info 1 and Actor Info 2

---

src/components/SignUp/Privacy.tsx

[DEV-253]
Removed 'click below' to 'Tap the green “Accept &  Continue” button to agree with our terms and privacy policy.'

[DEV-253] updated verbage for accept and continue

---

src/components/SignUp/Privacy.tsx

[DEV-253] Small Copy Fix

---

src/components/SignUp/AdditionalSkills.tsx
src/components/SignUp/Awards.tsx
src/components/SignUp/SignUp2Footer.tsx
src/pages/SignUp2.tsx

[DEV-151](https://artistguide.atlassian.net/browse/DEV-151)
- Added final flow sign up 2 step 5 for "Awards or Recognition"
- Added Go to Profile button
- Minor edit on Additional Skills page to remove < br > tag

[Dev-151] Added Final Flow Step Awards or Recognition

---

src/components/SignUp/Basics.tsx

[DEV-252](https://artistguide.atlassian.net/browse/DEV-252)
Updated spacing css between checkbox and password input field

[DEV-252] Updated Spacing between Checkbox and Password Input Field

---

package-lock.json
src/genericComponents/Input.tsx

[DEV-251] Textfield Shadows Removed
Drop shadows removed from text input fields

[DEV-251] Textfield Shadows Removed

---

src/components/SignUp/Landing.tsx
src/components/SignUp/Privacy.tsx

[DEV-264](https://artistguide.atlassian.net/browse/DEV-264)
[DEV-263](https://artistguide.atlassian.net/browse/DEV-263)
Updated the verbiage for both panel to `All the Above`. Also updated the privacy link to open on a new tab.
Verbiage update:
- [ N ] If you haven't made changes to `package.json`, `package-lock.json` is not present in this PR
- [ Y ] You have tested these changes locally by running the app and letting it build successfully
- [ Y ] Eslint ran successfully upon commit and `--force` was not used to force this PR

[DEV-263][DEV-264] updated verbiage and link opens on new tab

---

src/components/SignUp/OffstageRoles.tsx
src/genericComponents/GenericAccordion.tsx

[DEV-256](https://artistguide.atlassian.net/browse/DEV-256)
Added padding spacing between accordions in sign up flow step: So what do you like doing?

[DEV-256] Added padding spacing between accordions

---

src/components/SignUp/ActorInfo1.tsx
src/components/SignUp/Awards.tsx
src/components/SignUp/Demographics.tsx
src/components/SignUp/ProfilePhoto.tsx
src/components/SignUp/SignUpFooter.tsx
src/components/SignUp/Upcoming.tsx
src/pages/SignUp.tsx
src/pages/SignUp2.tsx

[DEV-254](https://artistguide.atlassian.net/browse/DEV-254)
[DEV-267](https://artistguide.atlassian.net/browse/DEV-267)
[DEV-272](https://artistguide.atlassian.net/browse/DEV-272)
[DEV-274](https://artistguide.atlassian.net/browse/DEV-274)
[DEV-275](https://artistguide.atlassian.net/browse/DEV-275)
Bug fixes

[DEV-254][DEV-267][DEV-272][DEV-274][DEV-275] Bug Fixes

---

src/components/SignUp/SignUp2Footer.tsx
src/components/SignUp/SignUpFooter.tsx
src/components/SignUp/SignUpFooterStyles.tsx
src/theme/styleVars.ts

[DEV-183](https://artistguide.atlassian.net/browse/DEV-183)
Footer Redesign

[DEV-183] Footer Redesign

---

src/components/SignUp/Demographics.tsx

[DEV-273](https://artistguide.atlassian.net/browse/DEV-273)
- Updated UI in Demographics sign up flow;
- Added padding and formatting for dropdowns and inputs
- Changed placeholder texts
N/A

[DEV-273] Updated UI in Demographics sign up flow

---

src/components/SignUp/Group/index.tsx
src/components/SignUp/Individual/Demographics.tsx
src/components/SignUp/Individual/OffstageRoles.tsx
src/components/SignUp/Individual/ProfilePhoto.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/SignUpFooter.tsx
src/components/layout/CardBox.tsx
src/pages/App.tsx

[DEMO] Saving Sign Up Flow 1A in Firebase

[DEMO] Saving Sign Up Flow 1A in Firebase

---

src/components/SignUp/Individual/Demographics.tsx
src/components/SignUp/Individual/index.tsx
src/pages/Profile.tsx

[DEV-225](https://artistguide.atlassian.net/browse/DEV-225)
Profile component design and dynamic data, v1

[DEV-225] Profile Component V1

---

src/components/SignUp/Individual/Demographics.tsx
src/components/SignUp/Individual/index.tsx
src/components/layout/Header.tsx
src/pages/App.tsx
src/pages/Login.tsx
src/pages/Profile.tsx
src/theme/styleVars.ts
src/utils/validation.ts

[DEMO] Functional Login

---

src/pages/Login.tsx

Updating the login page:
1. Styled button
2. Error handling for login

[NO-TICKET] Login Page Updates

---

src/components/SignUp/Group/index.tsx
src/components/SignUp/Individual/Basics.tsx
src/components/SignUp/Individual/Training.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/SignUp2Footer.tsx
src/components/SignUp/SignUpFooter.tsx
src/pages/SignUp2.tsx

[FIX] Fix Sign Up Flow 2nd Half Footer and Add Firebase Func

[FIX] Fix Sign Up Flow 2nd Half Footer and Add Firebase Func

---

src/components/SignUp/Individual/AdditionalSkills.tsx
src/components/SignUp/Individual/Awards.tsx
src/components/SignUp/Individual/Credits.tsx
src/components/SignUp/Individual/Training.tsx
src/components/SignUp/Individual/Upcoming.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/SignUp2Footer.tsx
src/genericComponents/Input.tsx
src/pages/Profile.tsx
src/pages/SignUp2.tsx

Functioning second half of individual signup flow

[SIGNUP] Functioning Second Half of Individual Signup Flow

---

package-lock.json
package.json

[NO-TICKET] Upgrade node-sass to 7.0.3

[NO-TICKET] Upgrade node-sass to 7.0.3

---

src/components/SignUp/Individual/Demographics.tsx
src/components/SignUp/Individual/SignUp2.tsx
src/components/SignUp/Individual/SignUp2Footer.tsx
src/components/SignUp/Individual/SignUpFooter.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/SignUp2Footer.tsx
src/pages/App.tsx
src/pages/Profile.tsx
src/pages/SignUp.tsx
src/utils/goToTop.ts

Implementing suggestions from the UX feedback

[UX] Sign Up Flow Feedback

---

src/pages/Donate.tsx

chore: update donation embed

---

src/components/Profile/Form/Inputs.tsx
src/components/Profile/Individual.tsx
src/components/layout/PageContainer.tsx

Minor Updates to Individual Profile

---

src/components/SignUp/Individual/SignUpFooter.tsx
src/components/layout/Footer.tsx
src/pages/Donate.tsx

Fixing signup back button functionality 

[HOTFIX] Fix Sign Up Back Button

---

src/components/Profile/Individual.tsx
src/components/SignUp/AccountType.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/Privacy.tsx

[DEV-285](https://artistguide.atlassian.net/browse/DEV-285)
Small fixes based on Anna's sign-up feedback

[DEV-285] Pt 1: Small Fixes

---

src/pages/App.tsx
src/pages/ForgotPassword.tsx
src/pages/Login.tsx

[FEAT] Reset Password Flow

---

src/components/Profile/Company/Production/ActiveProduction.tsx
src/components/Profile/Individual.tsx
src/genericComponents/GenericAccordion.tsx
src/pages/App.tsx
src/pages/Profile.tsx

[PROFILE] Show Real Profile Data + Rough Styling

[PROFILE] Show Real Profile Data + Rough Styling

---

src/components/Profile/Individual.tsx
src/components/Profile/shared/styles.ts
src/components/SignUp/AccountType.tsx
src/components/SignUp/SignUpStyles.tsx
src/pages/SignUp.tsx

[SIGN-UP] Launch Ready
- Profile complete message
- Mobile warning
- Profile styling improvements

[SIGN-UP] Launch Ready - Individual

---

src/components/SignUp/AccountType.tsx

[HOTFIX] Launch Sign Up Fix

---

src/components/Home/EmailList.tsx
src/components/SignUp/Individual/Basics.tsx
src/components/SignUp/Individual/SignUpFooter.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/Individual/types.ts
src/utils/marketing.ts

[LGL] Marketing Improvements

---

src/components/Profile/Individual.tsx
src/components/SignUp/AccountType.tsx
src/components/layout/ForArtists.tsx
src/components/layout/Header.tsx

[1.0.0] Public Beta Launch for Artist Signup

[1.0.0] Public Beta Launch for Artist Signup

---

package-lock.json
package.json

[1.0.0] Package Release

---

src/components/Profile/Individual.tsx
src/components/SignUp/Individual/ProfilePhoto.tsx
src/components/SignUp/Individual/Upcoming.tsx
src/utils/hasNonEmptyValues.ts

[HOTFIX] Unique Picture Naming

[HOTFIX] Unique Picture Naming

---

src/components/Profile/Individual.tsx
src/utils/hasNonEmptyValues.ts

[HOTFIX] In case of empty objects in individual profile

[HOTFIX] In case of empty objects in individual profile

---

package-lock.json
package.json
src/components/SignUp/AccountType.tsx
src/pages/SignUp.tsx

[COMPANY] Soft Launch with Param

[COMPANY] Soft Launch with Param

---

src/components/SignUp/AccountType.tsx

[HOTFIX] Company Soft Launch Fix

[HOTFIX] Company Soft Launch Fix

---

src/pages/Event.tsx

add scrolling to tickets iframe

---

src/components/Profile/Individual/IndividualCredits.tsx
src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/ActorInfo2.tsx
src/components/SignUp/Individual/Credits.tsx
src/components/SignUp/Individual/SignUp2.tsx
src/components/SignUp/Individual/SignUp2Footer.tsx
src/components/SignUp/Individual/Training.tsx
src/components/SignUp/Individual/types.ts
src/pages/FAQ.tsx
src/pages/TOS.tsx

[PROFILE] Support Multiple Training Institutions

[PROFILE] Support Multiple Training Institutions

---

public/index.html
src/components/Profile/Individual/EditPersonalDetails.tsx
src/components/Profile/Individual/index.tsx
src/components/Profile/Individual/types.ts
src/components/SignUp/Individual/ActorInfo1.tsx
src/components/SignUp/Individual/AdditionalSkills.tsx
src/components/SignUp/Individual/Awards.tsx
src/components/SignUp/Individual/types.ts
src/pages/Donate.tsx

[DEV-266](https://artistguide.atlassian.net/browse/DEV-266) Scratch ally wording 
[DEV-298](https://artistguide.atlassian.net/browse/DEV-298) All sections are editable except for Training
[NO-TICKET] New GiveButter Campaign

[DEV-266][DEV-298] Part 1: Profile Edit Progress + New GiveButter

---

src/components/Profile/Company/Edit.tsx
src/components/SignUp/Company/index.tsx
src/pages/Donate.tsx

[DEV-288](https://artistguide.atlassian.net/browse/DEV-288)

[DEV-288] Theater Edit: Email Address Validation

---

src/components/Profile/Company/Production/Manage/ManageProduction.tsx
src/components/Profile/Company/Production/Manage/ManageProductionRoles.tsx
src/components/Profile/Company/Production/Roles/RoleModal.tsx
src/utils/lookups.ts

add ability to delete show and role

---

src/components/Profile/Company/Production/AddProduction.tsx
src/components/Profile/Company/Production/Manage/ManageProduction.tsx
src/components/Profile/Company/Production/Manage/ManageProductionBasic.tsx
src/components/Profile/Company/Production/Roles/RoleModal.tsx
src/components/Profile/Company/types.ts
src/components/Profile/Form/Inputs.tsx

[DEV-292](https://artistguide.atlassian.net/browse/DEV-292) Casting Director Fields
[DEV-293](https://artistguide.atlassian.net/browse/DEV-292) Role Rate Fields

[DEV-292][DEV-293] Theaters: Add Casting Director and Role Rate Fields

---

src/components/Profile/Form/Inputs.tsx

[DEV-296](https://artistguide.atlassian.net/browse/DEV-296) Fix Datepicker Component - Selected Date

[DEV-296] Fix Datepicker Component - Selected Date

---

src/components/Profile/Individual/index.tsx
src/components/Profile/shared/ImageUploadModal.tsx

[DEV-299](https://artistguide.atlassian.net/browse/DEV-299)

[DEV-299] Image Upload Modal Component (In Progress)

---

src/components/Profile/Individual/index.tsx

[HOTFIX] Profile Request Fix

---

README.md
package-lock.json

[NODE] 18.13.0

---

src/components/Profile/Company/Production/Roles/RoleModal.tsx
src/components/Profile/Company/types.ts
src/components/Profile/Form/Inputs.tsx
src/components/Profile/shared/offstageRolesOptions.ts
src/components/Profile/shared/profile.types.ts
src/components/SignUp/Individual/OffstageRoles.tsx
src/pages/Logout.tsx

[OFF-STAGE] Share off-stage roles between Individual and Company

[OFF-STAGE] Share off-stage roles between Individual and Company

---

src/components/WhoWeAre/bios.ts

Fixed a typo in my own bio

---

src/components/FAQ/QandA.tsx
src/components/FAQ/questions.tsx
src/components/layout/Collapsible.tsx
src/pages/FAQ.tsx
src/pages/WhoWeAre.tsx

[DEV-316](https://artistguide.atlassian.net/browse/DEV-316))
Updated FAQs and made them collapsible
Made a generic collapsible component

Dev 316 faq update

---

src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/SignUpFooter.tsx
src/pages/Donate.tsx
src/pages/Profile.tsx

[DEV-319](https://artistguide.atlassian.net/browse/DEV-319)
1. Replace LGL with Zeffy Donate Form
2. Fix Existing Email Message for Sign Up
3. Fix Profile Loading Error when there are no upcoming performances yet

[DEV-319] Replace LGL with Zeffy Donate Form and Profile Fixes

---

src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/ActorInfo.tsx
src/components/SignUp/Individual/SignUpFooter.tsx
src/components/SignUp/Individual/index.tsx
src/components/SignUp/Individual/types.ts

[DEV-327](https://artistguide.atlassian.net/browse/DEV-327)
Simplify Individual Sign-Up Flow (On-Stage)

[DEV-327] Simplify Individual Sign-Up Flow (On-Stage)

---

src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/ActorInfo.tsx
src/components/SignUp/Individual/index.tsx
src/genericComponents/GenericAccordion.tsx

[DEV-329](https://artistguide.atlassian.net/browse/DEV-329)
[DEV-330](https://artistguide.atlassian.net/browse/DEV-330)
Simplify Individual Sign-Up Flow (Off-Stage and Both)

[DEV-329][DEV-330] Simplify Individual Sign-Up Flow (Off-Stage and Both)

---

package-lock.json
package.json
src/components/SignUp/Individual/ActorInfo.tsx

[DEV-333](https://artistguide.atlassian.net/browse/DEV-333)
This is just Part A until we figure out profile photo bugs for individuals

[DEV-333] Sign-Up Flow Clean-Up - Part A

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/CompanyMatchList.tsx
src/components/Matches/MatchesFilterBar.tsx
src/components/Matches/MatchesList.tsx
src/components/Matches/MatchesPageContainer.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/types.ts
src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/types.ts
src/context/MatchContext.tsx
src/context/firebaseUtils.ts
src/pages/App.tsx
src/pages/Matches.tsx
src/pages/SignUp.tsx
src/utils/marketing.ts

[DEV-360](https://artistguide.atlassian.net/browse/DEV-360)
Adding in the initial Matching infrastructure. There are some scattered TODOs for supporting Talent searching for Roles, but the basic flow for Companies searching for Talent should be ready to fill in the experience for.
Included in this PR is:
1. A firebase util for searching for talent matches based on filters, with a few other helpful state values like "loading"
2. The Matches context/provider which wraps the matching experience, loads matches based on default filters, and updates matches when filters change. It provides state values for loading, matches, filters, and a function to update filters
3. The high level components for the matching page, including the sidebar filters, the matches list, and the two …

[DEV-360] Initial Matching Infrastructure

---

src/components/layout/Header.tsx

[DEV-391](https://artistguide.atlassian.net/browse/TICKET)
CAG Website - Remove Headshot Event

CAG Website - Remove Headshot Event

---

package-lock.json

[HOTFIX] Fix CI/CD With Synced Package Lock

[HOTFIX] Fix CI/CD With Synced Package Lock

---

src/components/Matches/MatchesFilterBar.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Profile/Company/Production/ActiveProduction.tsx
src/components/Profile/Company/Production/Manage/ManageProduction.tsx
src/components/Profile/Company/Production/Manage/ManageProductionRoles.tsx
src/components/Profile/Company/Production/Roles/RoleCard.tsx
src/context/MatchContext.tsx
src/pages/App.tsx
src/pages/Matches.tsx
src/utils/firebaseUtils.ts

[DEV-360](https://artistguide.atlassian.net/browse/DEV-360)
Complete flow from role to matches page
Connect first role to filters bar 
Display matches on page

[DEV-360] Part 3: Showing Matches on Page and Connect Role to Filter Bar

---

src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/types.ts
src/components/Profile/shared/offstageRolesOptions.ts
src/context/MatchContext.tsx
src/utils/firebaseUtils.ts
tsconfig.json

[DEV-362](https://artistguide.atlassian.net/browse/DEV-362)
Filtering profiles for matches page. Includes multiple queries to handle filter vs profile value types and Firebase limitations, with intersection logic to only return profiles present across all results.

[DEV-362] Filtering Matches Based on Role - Part A

---

src/components/Matches/MatchesFilterBar.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Profile/Company/Production/Manage/ManageProductionRoles.tsx
src/context/MatchContext.tsx
src/pages/App.tsx
src/pages/Matches.tsx
src/utils/firebaseUtils.ts

[DEV-362](https://artistguide.atlassian.net/browse/DEV-362)
Adding union and special skills filters to filter bar. 
Added routing for roles for matches.
N/A

[DEV-362] Filters and Role Routing - Part 2

---

src/components/Matches/MatchesFilterBar.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/utils/firebaseUtils.ts

[DEV-364](https://artistguide.atlassian.net/browse/DEV-364)
[DEV-365](https://artistguide.atlassian.net/browse/DEV-365)
Initial accept/decline artist functionality, using the new collection in Firebase

[DEV-364][DEV-365] Initial Match Accept/Decline Functionality - Part 1

---

src/components/Matches/MatchesFilterBar.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/types.ts
src/context/MatchContext.tsx
src/utils/firebaseUtils.ts

[DEV-364](https://artistguide.atlassian.net/browse/DEV-364)
[DEV-365](https://artistguide.atlassian.net/browse/DEV-365)
Adding filter functionality based on match status
N/A

[DEV-364][DEV-365] Match Status Filter - Part 2

---

src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/api.ts
src/components/Messages/MessageThreads.tsx
src/components/Messages/types.ts
src/components/Profile/Company/api.ts
src/components/Profile/shared/api.ts
src/context/MatchContext.tsx
src/context/MessageContext.tsx
src/pages/Messages.tsx

[DEV-400](https://artistguide.atlassian.net/browse/DEV-400)

[DEV-400] Part 1: Get Messages Container and API Calls Working

---

src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/api.ts
src/components/Messages/MessageThread.tsx
src/components/Messages/MessageThreads.tsx
src/components/Messages/MessagesContainer.tsx
src/components/Messages/MessagesPagination.tsx
src/components/Messages/api.ts
src/components/Messages/types.ts
src/context/MessageContext.tsx
src/routes/Messages.tsx
src/routes/app-routes.tsx

[DEV-400](https://artistguide.atlassian.net/browse/DEV-400)
Flow to messages, including confirmation modal, visible threads, and new message based on match.

[DEV-400] Part 2: Flow to Threads/Messages

---

package-lock.json
src/components/layout/Header.tsx

No ticket, Anna asked: QQ: can we add a link to the "Silent Auction" under the "CAG-BARET" header in the navigation bar? Like a drop down? Here's the link to the form https://www.zeffy.com/ticketing/5a15d35d-d24e-4a21-926c-1acaec989b6e

silent auction dropdown

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/MatchesPageContainer.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Messages/MessageThread.tsx
src/components/Messages/MessageThreads.tsx
src/components/Messages/api.ts
src/components/Messages/types.ts
src/components/Profile/Company/api.ts
src/components/Profile/Company/types.ts
src/components/Profile/shared/api.ts
src/components/SignUp/Individual/index.tsx
src/components/SignUp/Individual/types.ts
src/context/MatchContext.tsx
src/context/MessageContext.tsx

[DEV-383](https://artistguide.atlassian.net/browse/DEV-383)
Clean up of messages and get initial emails working with plugin

[DEV-383] Part 1: Messaging Final and Initial Emails

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/api.ts
src/components/Matches/types.ts
src/components/Messages/MessageThread.tsx
src/components/Messages/MessageThreads.tsx
src/components/Messages/api.ts
src/components/Messages/messages.ts
src/components/Profile/Company/Production/AddProduction.tsx
src/components/Profile/Company/index.tsx
src/components/Profile/shared/api.ts
src/context/MessageContext.tsx
src/context/UserContext.tsx
src/hooks/useProfileData.ts

[DEV-383](https://artistguide.atlassian.net/browse/DEV-383)
Sending emails for talent and companies
Adding Thread Actions
Fixing account id vs uid mix-ups

[DEV-383] Part 2: Talent Emails and Thread Actions

---

src/components/Messages/MessageThread.tsx
src/components/Messages/MessagesContainer.tsx

[DEV-383](https://artistguide.atlassian.net/browse/DEV-383)
Add disabled logic for thread action buttons
Send emails from thread action buttons 
Force reload the route after thread action buttons

[DEV-383] Part 3: Final Messaging Fixes

---

src/components/layout/Header.tsx

Added digital program to website for cag-baret

Added digital program

---

index.html
src/components/Profile/Individual/index.tsx

[HOTFIX] Try Base Href

---

index.html
src/components/FAQ/homeFAQ.tsx
src/components/FAQ/questions.tsx
src/components/layout/Footer.tsx
src/routes/Donate.tsx
src/routes/Home.tsx
src/routes/Redesign.tsx
src/routes/TheaterResources.tsx
src/routes/app-routes.tsx

Changed as many as I saw
That word means nothing to me anymore

Theater to Theatre

---

src/components/Redesign/Values.tsx

I added spaces before certain colors. This is how I was able to fix it locally. Please don't judge I understand this is not ideal but I might as well try.

Added Spaces

---

src/components/Redesign/Values.tsx

This worked locally, hope it works here

Deleted Spaces

---

src/components/Redesign/Values.tsx

Changed the colors I have no idea what is going on

changed colors

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Matches/api.ts
src/context/MatchContext.tsx

[HOTFIX] Don't Send Messages/Emails for Decline and Add Matching Logs

---

src/components/Matches/TalentMatchCard.tsx
src/components/Matches/TalentMatchList.tsx
src/components/Matches/api.ts
src/context/MatchContext.tsx

[HOTFIX] Matching Fixes

---

src/components/Profile/Company/Production/AddProduction.tsx

Add a show is not saving anymore. When you click Save Show, everything entered is cleared from the page and not saved. 
The account was account+id, we are using uid

Add a show doesn't save

---

src/components/Profile/Individual/index.tsx

[LAUNCH] Update Talent Profile Message

---

src/components/Redesign/Values.tsx

Mobile value

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/TalentMatchCard.tsx
src/components/Profile/Individual/index.tsx
src/components/SignUp/Individual/ActorInfo.tsx

[DEV-410](https://artistguide.atlassian.net/browse/DEV-410)
[DEV-414](https://artistguide.atlassian.net/browse/DEV-414)
[DEV-417](https://artistguide.atlassian.net/browse/DEV-417)
Fixing the following minor bugs:
1. Artist Sign Up - able to select more than 3 age range options. Fixed
2. Artist Profile - add training and add upcoming feature buttons redirected to "#" (left profile page and went to home page). Fixed
3. Matches - bottom of text cut off due to exact height of cards. Fixed

[DEV-410][DEV-414][DEV-417] Minor Bug Fixes

---

src/components/FAQ/homeFAQ.tsx
src/components/layout/Header.tsx
src/routes/Home.tsx

End of Year Donate Link

---

src/components/Matches/CompanyMatchCard.tsx
src/components/Matches/CompanyMatchesFilterBar.tsx
src/components/Matches/MatchesPageContainer.tsx
src/components/Matches/TalentMatchCard.tsx

[DEV-430](https://artistguide.atlassian.net/browse/DEV-430)
[DEV-432](https://artistguide.atlassian.net/browse/DEV-432)
1. Making more obvious style decisions on match cards that have already been accepted or declined
2. Making some minor improvements to card usability for some screen sizes between md and xl

[DEV-430][DEV-432] Match Card Improvements

---

src/components/layout/Header.tsx

[DEV-435](https://artistguide.atlassian.net/browse/DEV-435)
1. Set donate link back to donate page
2. Remove CAG Baret links

[DEV-435] Set Donate Link Back to Donate Page

---

src/routes/SignUp.tsx

[DEV-437](https://artistguide.atlassian.net/browse/DEV-437)
Add Company Flag Logic Back for Theatre Signup Flow

[DEV-437] Add Company Flag Logic Back for Theatre Signup Flow

---

src/components/FAQ/homeFAQ.tsx
src/routes/Donate.tsx
src/routes/Home.tsx
src/utils/marketing.ts

NO TICKET
3/19/25 - Minor Zeffy URL and Home FAQ Updates
N/A

3/19/25 - Minor Zeffy URL and Home FAQ Updates

---

src/components/layout/Header.tsx

[TEMP] Add Headshot Zeffy Event Link to Navbar

[TEMP] Add Headshot Zeffy Event Link to Navbar

---

src/components/shared/EventCard.tsx
src/components/shared/index.tsx
src/routes/Events.tsx
src/routes/app-routes.tsx

[DEV-438](https://artistguide.atlassian.net/browse/DEV-438)
Initial Events Page work. Need to sit with Anna and talk about adding test events in to make sure they look good. Also need to make style adjustments to the cards still, especially the icons.

[DEV-438] Events Page Initial

---

src/components/layout/Footer.tsx
src/components/layout/Header.tsx
src/components/shared/Pagination.tsx

[DEV-438](https://artistguide.atlassian.net/browse/DEV-438)
Make Events page live
Hotfix on TS error blocking pipeline

[DEV-438] Events Page Live

---

src/components/PublicShows/PublicRoleCardSkeleton.tsx
src/components/PublicShows/PublicShowCardSkeleton.tsx
src/components/PublicShows/PublicShowDetailSkeleton.tsx

[HOTFIX] Fixing More Circular PropTypes Errors in StyledComponents

[HOTFIX] Fixing More Circular PropTypes Errors in StyledComponents

---

src/components/layout/Footer.tsx
src/components/layout/Header.tsx

comment link

---

src/components/shared/EventCard.tsx

[HOTFIX] Specify CST Timezone for Event Date

[HOTFIX] Specify CST Timezone for Event Date
